//
//  atgn2_.c
//  ViperNEC
//
//  Created by Dylan Crocker on 6/28/14.
//  Copyright 2014 Viper Science
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

#include <math.h>

/**
 * This function (atgn2_) is a cleaned up version of the function generated by 
 * f2c. 
 *
 * Original FORTRAN documentation:
 * ATGN2 IS ARCTANGENT FUNCTION MODIFIED TO RETURN 0. WHEN X=Y=0.
 *
 * Original NEC documentation:
 *
 *   PURPOSE
 *     To return zero when both arguments of a two-argument arctangent function
 *     are zero. (Most standard arctangent functions &ive an error return when 
 *     both arguments are zero.)
 *
 *   METHOD
 *     System function ATAN2 is used except when both arguments are zero, in
 *     which case the value zero is returned. The value returned is the angle 
 *     (in radians) whose sine is X and cosine is Y.
 *
 * @param x first argument
 * @param y second argument
 * @since v1.0
 */
double atgn2_(double *x, double *y) {
  if ((*x == 0.0) && (*y == 0.0)) {
    return 0.0;
  }
  return atan2(*x, *y);
}
