//
//  cang_.c
//  ViperNEC
//
//  Created by Dylan Crocker on 6/28/14.
//  Copyright 2014 Viper Science
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

#include "types.h"
#include "macro.h"
#include "util.h"

/**
 * This function (cang_) is a cleaned up version of the function generated by
 * f2c.
 *
 * Original FORTRAN documentation:
 * CANG RETURNS THE PHASE ANGLE OF A COMPLEX NUMBER IN DEGREES.
 *
 * Original NEC documentation:
 *
 *   PURPOSE
 *     To calculate the phase angle of a complex number in degrees.
 *
 *   METHOD
 *     z = x + jy
 *     phi = [arctan (y/x)]*57.29577951
 *
 * @param z Input complex quantity
 * @since v1.0
 */
double cang_(complex_t *z) {
  return RAD_TO_DEG(atgn2_(&(z->i), &(z->r)));
}
