//
//  db10_0_.c
//  ViperNEC
//
//  Created by Dylan Crocker on 6/28/14.
//  Copyright 2014 Viper Science
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

#include <math.h>

/**
 * This function (db10_0_) is a cleaned up version of the function generated by
 * f2c. This was originally one function in FORTRAN with multiple entry points 
 * for DB10 and DB20. The f2c program has split them up into separete functions 
 * wiech calling a common function (dB10_0_) and specifiying the calculation
 * with an input paramter.
 *
 * Original FORTRAN documentation:
 * FUNCTION DB-- RETURNS DB FOR MAGNITUDE (FIELD) OR MAG**2 (POWER).
 *
 * Origianl NEC documentation:
 *
 *   PURPOSE
 *     To convert an input magnitude quantity (field) or magnitude squared
 *     quantity (power) into decibels.
 *
 *   METHOD
 *     For a squared quantity, the decibel conversion is:
 *
 *         Qdb = 10*log10(Q^2) (Q^2 input)
 *
 *     and for an unsquared quantity,
 *     
 *         Qdb = 20*log10(Q)
 *
 *   DB1O is used for the squared quantity while the entry DB20 is used for the
 *   quantity which is not squared.
 *
 * @param n Specifies the calculation: 1 -> 10*log10(x), 2 -> 20*log10(x).
 * @param x Value to be converted to dB.
 * @since v1.0
 */
double db10_0_(int n, double *x)
{
  // If the number is really small just return close to negative infinity.
  if (*x < 1e-20) { return -999.99f; }
  
  // Coef. (10 for pwr, 20 for voltage)
  double f = (n == 1) ? 20.f : 10.f;
  
  // Calculate and return dB
  return f * log10(*x);
}

/**
 * Calculate power in dB.
 *   
 * Example: 10*log10(mag)
 *
 * @param x Value to be converted to dB.
 * @since v1.0
 */
double db10_(double *x) {
  return db10_0_(0, x);
}

/**
 * Calculate dB value for fields, voltage, etc.
 *   
 * Example: 20*log10(mag)
 *
 * @param x Value to be converted to dB.
 * @since v1.0
 */
double db20_(double *x) {
  return db10_0_(1, x);
}
