// second_.c
// This function matches the prototype expected by the c code generated by the
// F2c conversion tool. It sets the specified input to the CPU time in seconds.
// The computation time is computed by tubtracting the difference between
// subsequent calls to second_.
//
//  Created by Dylan Crocker on 10/20/2018.
//  Copyright 2018 Viper Science LLC
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

#include <time.h>
int second_(double *t) {
    clock_t sample = clock();
    *t = (double) sample / CLOCKS_PER_SEC;
    return 0;
}
