//
//  NECGroundGridBlock.h
//  ViperNEC
//
//  Created by Dylan Crocker on 1/7/15.
//  Copyright 2015 Viper Science
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//  limitations under the License.
//

#ifndef VIPERNEC_NECGROUNDGRIDBLOCK_H
#define VIPERNEC_NECGROUNDGRIDBLOCK_H

#include "types.h"

/**
 *  Original NEC documentation:
 *
 *  <ul>COMMON/GGRID/</ul> AR1(11, 10, 4) AR2(17, 5, 4) AR3(9, 8, 4), EPSCF,
 *      DXA(3), DYA(3), XSA(3), YSA(3), NXA(3), NYA(3)
 *
 *  <ul>Routines Using /GGRID/</ul>
 *      MAIL, GFIL, GFOUT, INTRP
 *      Variables are defined under subroutine INTRP.
 *
 *  @since v1.0
 */
typedef struct ggrid_block {
  
  /**
   *  The three interpolation tables (generated by SOMNEC) are stored in the
   *  following three arrays: ar1 (grid 1), ar2 (grid 2), ar3 (grid 3).
   */
  complex_t ar1[440]; /* was [11][10][4] */
  complex_t ar2[340]; /* was [17][5][4] */
  complex_t ar3[288]; /* was [9][8][4] */
  
  /**
   *  e1 - j*sig/(w*e0)
   */
  complex_t epscf;
  
  /**
   *  Array of delta x values
   */
  double dxa[3];
  
  /**
   *  Array of delta y values
   */
  double dya[3];
  
  /**
   *  Array of values of x at lower edge of each grid (si)
   */
  double xsa[3];
  
  /**
   *  Array of values of y at lower edge of each grid (ti)
   */
  double ysa[3];
  
  /**
   *  The number of x values in each grid
   */
  int nxa[3];
  
  /**
   *  The number of y values in each grid
   */
  int nya[3];
  
} NECGroundGridBlock;

#endif
